N_S = 5  # buffer size
N_i = 5  # update
N_t = 10  # average update
K = 50
LAMBDA_P = 10
LAMBDA_S = 0.3
LAMBDA_B = 1e-2
LAMBDA_I = 1e-4
LAMBDA_N = 0.2 * N_S
D = 3  # dimension of X
d = 2  # dimension of F
